# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from UR3e_RG2_ER5_vision/UR3Msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class UR3Msg(genpy.Message):
  _md5sum = "58d1707d0143a3a0da3fcde7e0164d11"
  _type = "UR3e_RG2_ER5_vision/UR3Msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string Obj_name
geometry_msgs/Pose Obj_Pose
float64 Radius
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['Obj_name','Obj_Pose','Radius']
  _slot_types = ['string','geometry_msgs/Pose','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Obj_name,Obj_Pose,Radius

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UR3Msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Obj_name is None:
        self.Obj_name = ''
      if self.Obj_Pose is None:
        self.Obj_Pose = geometry_msgs.msg.Pose()
      if self.Radius is None:
        self.Radius = 0.
    else:
      self.Obj_name = ''
      self.Obj_Pose = geometry_msgs.msg.Pose()
      self.Radius = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Obj_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.Obj_Pose.position.x, _x.Obj_Pose.position.y, _x.Obj_Pose.position.z, _x.Obj_Pose.orientation.x, _x.Obj_Pose.orientation.y, _x.Obj_Pose.orientation.z, _x.Obj_Pose.orientation.w, _x.Radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Obj_Pose is None:
        self.Obj_Pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Obj_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Obj_name = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.Obj_Pose.position.x, _x.Obj_Pose.position.y, _x.Obj_Pose.position.z, _x.Obj_Pose.orientation.x, _x.Obj_Pose.orientation.y, _x.Obj_Pose.orientation.z, _x.Obj_Pose.orientation.w, _x.Radius,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Obj_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.Obj_Pose.position.x, _x.Obj_Pose.position.y, _x.Obj_Pose.position.z, _x.Obj_Pose.orientation.x, _x.Obj_Pose.orientation.y, _x.Obj_Pose.orientation.z, _x.Obj_Pose.orientation.w, _x.Radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Obj_Pose is None:
        self.Obj_Pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Obj_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Obj_name = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.Obj_Pose.position.x, _x.Obj_Pose.position.y, _x.Obj_Pose.position.z, _x.Obj_Pose.orientation.x, _x.Obj_Pose.orientation.y, _x.Obj_Pose.orientation.z, _x.Obj_Pose.orientation.w, _x.Radius,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
